### PR TITLE
Make payload generation complexity linear.

### PR DESCRIPTION
**Pull request by gukoff**
## Purpose

Make payload generation complexity linear. Currently it's quadratic, see #12
## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test

TBD

## What to Check

TBD
Verify that the following are valid
* ...

### CODE REVIEW

**Comment by gukoff** [comment]
This is the first iteration of the PR.

I haven't tested this change yet, and I haven't add proper comments to explain tokenization to the reader.

**Comment by gukoff** [comment]
Ready for review.

**Comment by TechPreacher** [comment]
Code looks good. Tried it out and it works fine. Looks good to me - thanks for the great contribution!

**Review by TechPreacher — APPROVED** [review]

**Comment by gukoff** [comment]
Continued in #18

**Pull request merged**
