### PR TITLE
Bugfix - Resolve Issue #33. Set a variable for the double value and get its String Representation

### PR DESCRIPTION
**Pull request by NikosKsygkis**
## Purpose

- This PR fixes the [issue #33](https://github.com/Azure-Samples/Iot-Telemetry-Simulator/issues/33)
- It fixes the test [ShouldSubstituteVariablesCorrectly](https://github.com/Azure-Samples/Iot-Telemetry-Simulator/blob/master/test/IotTelemetrySimulator.Test/TemplateVariableSubstitutionTest.cs#:~:text=%7D-,%5BTheory%5D,%7D,-public%20static%20IEnumerable) by setting a variable for the double value in the [GetTestData](https://github.com/Azure-Samples/Iot-Telemetry-Simulator/blob/master/test/IotTelemetrySimulator.Test/TemplateVariableSubstitutionTest.cs#:~:text=public%20static%20IEnumerable%3Cobject%5B%5D%3E%20GetTestData()) method and getting its string representation.

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

### CODE REVIEW

**Review by TechPreacher — APPROVED** [review]

**Comment by gukoff** [comment]
Maybe use [invariant culture](https://docs.microsoft.com/en-us/dotnet/core/run-time-config/globalization) instead?

Otherwise we will produce incorrect JSONs:

```
{"value": $doubleVal} 
```

will be evaluated into

```
{"value": 1,2} 
```

**Review by gukoff — DISMISSED** [review]
Approve 🐞 


Side note - should we enable this setting in all projects? I never really looked what the other projects do.

**Review by TechPreacher — APPROVED** [review]

**Comment by fbeltrao** [comment]
> Approve 🐞
> 
> Side note - should we enable this setting in all projects? I never really looked what the other projects do.

What if you want to have both neutral and culture aware values in same project?
I think that using the correct culture for each use case make the code explicitly, not hiding how the code behaves in a configuration file.

**Comment by gukoff** [comment]
> What if you want to have both neutral and culture aware values in same project?
I think that using the correct culture for each use case make the code explicitly, not hiding how the code behaves in a configuration file.

I agree that explicitness is better, and at the same time don't see how culture-awareness is useful for the telemetry simulator :)

@NikosKsygkis if you want to make it explicit, then in `TelemetryTemplate.cs`, line 92 we should do `Convert.ToString(result, CultureInfo.InvariantCulture)` instead of `result.ToString()`
 `

**Comment by gukoff** [comment]
@NikosKsygkis could you please also add a comment why we use `InvariantCulture` there?
Otherwise, someone might want to revert it to `.ToString()` in the future.

**Review by gukoff — DISMISSED** [review]

**Review by TechPreacher — DISMISSED** [review]

**Review by gukoff — APPROVED** [review]

**Pull request merged**
